-- First, create the table to store waitlist emails
create table waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on the table
alter table waitlist enable row level security;

-- Create a policy that allows ANYONE to insert into the waitlist
-- This allows anonymous users visiting your website to sumbit their email
create policy "Allow anonymous inserts"
  on waitlist for insert
  with check (true);

-- IMPORTANT SECURITY STEP: 
-- We ONLY created an insert policy for anonymous users.
-- We are INTENTIONALLY NOT creating a select/read policy.
-- This ensures that public users CANNOT query or view the list of emails.
-- Only you (via the Supabase dashboard) or authenticated admins can view the data.
